# Generated by Django 3.2.9 on 2021-12-19 19:49

from django.db import migrations, models
import django.db.models.deletion
import notes_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(default=notes_app.models.one_week_hence)),
                ('notes_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes_app.noteslist')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
