# Generated by Django 4.1.4 on 2022-12-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0005_alter_choice_id_alter_question_id_alter_quiz_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='date_created',
            field=models.DateTimeField(default=''),
        ),
    ]
