# Generated by Django 4.1.4 on 2022-12-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0006_alter_quiz_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='date_created',
            field=models.DateTimeField(),
        ),
    ]
